In [ ]:
空氣污染監測網 網頁爬蟲
如果利用原本的 Request 的方式，會發現怎麼拉都是空資料。原因在於資料一樣是透過 JavaScript 動態載入的。

In [1]:
# 打開瀏覽器

from selenium import webdriver
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup

In [2]:
browser = webdriver.Chrome(executable_path='chromedriver')

browser.get("http://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")

In [3]:
#模擬使用者操作行為，選擇/點擊

selectSite = Select(browser.find_element_by_id("ctl05_ddlSite"))
selectSite.select_by_value('29')
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2014')

browser.find_element_by_id('ctl05_btnQuery').click()

In [4]:
# 取得資料，丟到 BeautifulSoup 解析

html_source = browser.page_source

soup = BeautifulSoup(html_source, 'html.parser')
table = soup.find('table', class_='TABLE_G')
print(table)

<table align="Center" border="1" cellpadding="3" cellspacing="0" class="TABLE_G" id="ctl05_gv" rules="all" style="border-color:Black;border-width:1px;border-style:None;border-collapse:collapse;">
<tbody><tr style="color:Black;font-weight:normal;">
<th scope="col">監測項目</th><th scope="col">單位</th><th scope="col">監測日期</th><th scope="col">監測值</th><th scope="col">標註</th>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2014/01</td><td>4.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>2.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>3.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>3.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>3.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>3</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>3.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>3.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>3.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>2.80</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>2.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>3.10</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">CO</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2014/01</td><td>0.48</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>0.38</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>0.47</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>0.39</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>0.35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>0.27</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>0.22</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>0.23</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>0.31</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>0.35</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>0.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>0.42</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">O3</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2014/01</td><td>30.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>31.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>35.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>41.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>26.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>23.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>24.30</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>24.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>27.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>43.20</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>32.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>28.80</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">PM10</td><td class="no-alt" rowspan="12" valign="top">μg/m3</td><td>2014/01</td><td>72</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>50</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>74</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>64</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>39</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>34</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>32</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>47</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>69</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>67</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>60</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NOx</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2014/01</td><td>23.63</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>16.89</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>21.78</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>17.06</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>16.66</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>13.82</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>12.16</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>12.46</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>15.15</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>16.72</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>18.61</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>19.20</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2014/01</td><td>4.75</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>2.53</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>3.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>1.56</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>2.37</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>2.17</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>2.04</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>2.09</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>2</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>1.88</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>2.63</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>3.17</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2014/01</td><td>18.88</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>14.36</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>18.38</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>15.49</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>14.28</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>11.65</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>10.11</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>10.36</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>13.14</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>14.82</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>15.98</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>16.02</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">THC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr class="ALT" style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">NMHC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr style="color:Black;">
<td style="white-space:nowrap;">CH4</td><td>ppm</td><td> </td><td> </td><td>無此測項</td>
</tr>
</tbody></table>

In [ ]:
# 關閉瀏覽器
browser.quit();

In [ ]:
作業目標
根據範例 ，完成以下問題：

① 取出 台北市士林區 2018/01 – 2018/08 的 SO2 資料
② 取出 台北市士林區 2018/01 – 2018/08 的 SO2、CO 資料

In [ ]:
#1. 取出 台北市士林區 2018/01 – 2018/08 的 SO2 資料

In [ ]:
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup

In [5]:
browser = webdriver.Chrome(executable_path='chromedriver')

browser.get("http://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")

In [6]:
selectSite = Select(browser.find_element_by_id("ctl05_ddlSite"))
selectSite.select_by_value('11') #透過開發者工具(F12) 查找
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2018')

browser.find_element_by_id('ctl05_btnQuery').click()

In [7]:
html_source = browser.page_source

soup = BeautifulSoup(html_source, 'html.parser')
table = soup.find('table', class_='TABLE_G')
print(table)

<table align="Center" border="1" cellpadding="3" cellspacing="0" class="TABLE_G" id="ctl05_gv" rules="all" style="border-color:Black;border-width:1px;border-style:None;border-collapse:collapse;">
<tbody><tr style="color:Black;font-weight:normal;">
<th scope="col">監測項目</th><th scope="col">單位</th><th scope="col">監測日期</th><th scope="col">監測值</th><th scope="col">標註</th>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>1.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>1.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>2.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>2.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>3.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>2.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>2.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>2.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>2.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>1.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>1.90</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>1.80</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">CO</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2018/01</td><td>0.34</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>0.44</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>0.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>0.38</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>0.34</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>0.29</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>0.21</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>0.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>0.26</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>0.29</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>0.30</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>0.35</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">O3</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>33.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>32.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>38.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>31.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>29.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>18.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>26.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>29.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>45.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>32.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>30.70</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">PM10</td><td class="no-alt" rowspan="12" valign="top">μg/m3</td><td>2018/01</td><td>23</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>41</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>39</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>48</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>37</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>26</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>24</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>26</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>28</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>33</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>25</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>21</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NOx</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>14.17</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>19.43</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>18.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>15.24</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>15.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>13.79</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>11.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>14.75</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>12.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>12.45</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>13.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>14.56</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>3.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>4.48</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>4.93</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>2.60</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>2.26</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>2.41</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>2.68</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>2.68</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>2.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>2.13</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>2.71</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>3.42</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>10.77</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>14.95</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>13.56</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>12.64</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>12.94</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>11.38</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>8.92</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>12.08</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>10.33</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>10.71</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>11.15</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">THC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr class="ALT" style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">NMHC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr style="color:Black;">
<td style="white-space:nowrap;">CH4</td><td>ppm</td><td> </td><td> </td><td>無此測項</td>
</tr>
</tbody></table>

In [21]:
value = []
i = 0
while True:
    value.append({
        '月份:': table.find_all('td')[2+i*3].text,
        'SO2(ppb):': table.find_all('td')[3+i*3].text})
    i+=1
    if i == 7 :
        break

import pandas as pd
pd.DataFrame(value)

       月份: SO2(ppb):
0  2018/01      1.80
1  2018/02      1.90
2  2018/03      2.20
3  2018/04      2.30
4  2018/05      3.10
5  2018/06      2.70
6  2018/07      2.20

In [ ]:
# 2. 取出 台北市士林區 2018/01 – 2018/08 的 SO2、CO 資料

In [28]:
for i in range(0,len(table.find_all('td'))):
    if table.find_all('td')[i].text == 'CO' :
        print('CO is at :',i)
        position_CO = i
    if table.find_all('td')[i].text == 'SO2' :
        print('SO2 is at :',i)
        position_SO2 = i
    else :
        pass

SO2 is at : 0
CO is at : 38

In [31]:
value = []
i = 0
SO2_ms = table.find_all('td')[position_SO2+1].text
CO_ms = table.find_all('td')[position_CO+1].text
while True:
    value.append({
        '月份:': table.find_all('td')[2+i*3].text,
        'SO2('+SO2_ms+'):': table.find_all('td')[3+i*3].text,
        'CO('+CO_ms+'):':table.find_all('td')[position_CO+2+i*3].text})
    i+=1
    if i == 7 :
        break

import pandas as pd
pd.DataFrame(value)

       月份: SO2(ppb): CO(ppm):
0  2018/01      1.80  2018/01
1  2018/02      1.90  2018/02
2  2018/03      2.20  2018/03
3  2018/04      2.30  2018/04
4  2018/05      3.10  2018/05
5  2018/06      2.70  2018/06
6  2018/07      2.20  2018/07